version: '3.7'
services:
  api:
    container_name: vehicle_loans_api
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000
    # volumes:
    #   - ./api:/var/www/api
    #   - /var/www/api/vendor
    depends_on:
      - db
    networks:
      - local_network
    tty: true

  db:
    container_name: vehicle_loans_db
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: vehicle_loans
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33066:3306
    networks:
      - local_network
    tty: true

  frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
    container_name: vehicle_loans_frontend
    # volumes:
    #   - ./frontend:/var/www/frontend
    #   - /var/www/node_modules
    depends_on:
      - "api"
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
    networks:
      - local_network
    tty: true
    
networks:
  local_network:
    driver: bridge
